#!/usr/bin/env bash

# SPDX-License-Identifier: BSD-3-Clause
# Copyright 2023-2025 <Nitrux Latinoamericana S.C. <hello@nxos.org>>

set -eu

# -- Source APT commands as functions.
# shellcheck source=/dev/null

source /configs/scripts/others/apt-funcs


# -- Install NVIDIA "open" driver packages.

INSTALL_NVIDIA_OPEN_PKGS=(
    nvidia-open-driver-590
    nvidia-open-kernel-dkms-590
    nvidia-alternative-590
)

install "${INSTALL_NVIDIA_OPEN_PKGS[@]}"
