#!/usr/bin/env sh

# SPDX-License-Identifier: BSD-3-Clause
# Copyright 2024-2025 <Nitrux Latinoamericana S.C. <hello@nxos.org>>

set -e


# -- Enable NVIDIA Power Management Services.

LOGFILE="/var/log/nvidia-sleep.log"
echo "$(date) - $1" >> "$LOGFILE"

case "$1" in
    pre)
        /usr/bin/nvidia-sleep.sh suspend >> "$LOGFILE" 2>&1
        ;;
    post)
        /usr/bin/nvidia-sleep.sh resume >> "$LOGFILE" 2>&1
        ;;
esac
